### ISSUE TITLE
Transfers Module

### ISSUE THREAD

**Issue by kamfosica** [CGATechnologies/sct-smart-app#12]

**Comment by sammymuriuki** [comment]
Add Bar code scanning functionality in the transfer screen
The screen for paying HHs should show the Main recipient and Alt recipient photos and their national IDs
 When paying, there should be a field that shows whether it's the Main or Alt recipient that collected the money.

**Comment by sammymuriuki** [comment]
Reload transfer list onresume
Arrange transfers according to review state
